---
name: "HACS validate"

on:
  push:
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate-hassfest:
    name: "Hassfest validation"
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"
      - name: "validation"
        uses: "home-assistant/actions/hassfest@master"

  validate-hacs:
    name: "HACS validation"
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
